# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0002_auto_20161006_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageclass',
            name='short_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luggagesize',
            name='short_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luggagewheels',
            name='short_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
