# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0003_auto_20161006_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageclass',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luggagesize',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luggagewheels',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
