# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0004_auto_20161006_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggagephoto',
            name='luggage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='luggage.Luggage'),
        ),
    ]
