# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0005_auto_20161017_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('details', models.TextField()),
                ('features', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'luggage_luggage_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'luggage Translation',
            },
        ),
        migrations.RemoveField(
            model_name='luggage',
            name='details',
        ),
        migrations.RemoveField(
            model_name='luggage',
            name='features',
        ),
        migrations.AddField(
            model_name='luggagetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='luggage.Luggage'),
        ),
        migrations.AlterUniqueTogether(
            name='luggagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
