# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0006_auto_20161019_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageClassTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=256)),
                ('short_title', models.CharField(max_length=256)),
            ],
            options={
                'managed': True,
                'db_table': 'luggage_luggageclass_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'luggage class Translation',
            },
        ),
        migrations.CreateModel(
            name='LuggageSizeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=256)),
                ('short_title', models.CharField(max_length=256)),
            ],
            options={
                'managed': True,
                'db_table': 'luggage_luggagesize_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'luggage size Translation',
            },
        ),
        migrations.CreateModel(
            name='LuggageWheelsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=256)),
                ('short_title', models.CharField(max_length=256)),
            ],
            options={
                'managed': True,
                'db_table': 'luggage_luggagewheels_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'luggage wheels Translation',
            },
        ),
        migrations.RemoveField(
            model_name='luggageclass',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='luggageclass',
            name='title',
        ),
        migrations.RemoveField(
            model_name='luggagesize',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='luggagesize',
            name='title',
        ),
        migrations.RemoveField(
            model_name='luggagewheels',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='luggagewheels',
            name='title',
        ),
        migrations.AddField(
            model_name='luggagewheelstranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='luggage.LuggageWheels'),
        ),
        migrations.AddField(
            model_name='luggagesizetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='luggage.LuggageSize'),
        ),
        migrations.AddField(
            model_name='luggageclasstranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='luggage.LuggageClass'),
        ),
        migrations.AlterUniqueTogether(
            name='luggagewheelstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='luggagesizetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='luggageclasstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
