# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0008_auto_20161019_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Region'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Country'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Region'),
        ),
    ]
