# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0010_auto_20161019_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
