# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0011_order_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
