# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0017_auto_20161021_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_return_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luggage.ReturnTime'),
        ),
    ]
