# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0020_order_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
