# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0023_remove_invoice_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cnt',
        ),
    ]
