# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0024_remove_order_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
