# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-13 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0026_auto_20161213_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='days',
        ),
    ]
