# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0027_remove_order_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=256)),
                ('min_days', models.IntegerField(blank=True, null=True)),
                ('min_total', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, default=0, help_text=b'Percentage of discount (e.g. 15)')),
                ('free_days', models.IntegerField(blank=True, default=0)),
                ('expire', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
