# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0028_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
